### ISSUE TITLE
Search for online maps

### ISSUE THREAD

**Issue by erikgoe** [JulianSobott/NavEvent#20]
We need a textview (or the like) to search for maps. Otherwise onlinemaps will not be accessible

**Comment by Gametunes** [comment]
In addition to that the User should be abeld to open the mapselectactivity manually if he/she wishes to change the map
what happens if you are in  the area of 2 different Beacons?

**Comment by erikgoe** [comment]
Nearest will be choosen

**Comment by Gametunes** [comment]
Problem most likely solved, everybody is encouraged to test this!

**Comment by erikgoe** [comment]
Error with https://github.com/JulianSobott/NavEvent/commit/6d993923542ae78c7dc8d6bef8514718f9173e5f#diff-4edc6a0af7a67ea00dd29abb4e919089R18
ID does not exist anymore
