### ISSUE TITLE
Configuration steps for admins

### ISSUE THREAD

**Issue by erikgoe** [JulianSobott/NavEvent#24]
Which configuration steps should be visible on the website?

1. Go into the admin area by doing ...
2. Scan the qr-code with your phone (try to hold your camera parallel to the screen)
3. Prepare the beacon you want to configure:
3.1. Plugin the batteries
3.2. Be sure this beacon is the only one which is turned on in the local area
3.3. In the app, select the beacon name which should be associated with beacon device
3.4. Wait until the beacon was successfully configured or try again if it failed
3.4.1. You may have to enter a pin
3.5. Place the beacon device where you have defined it in your map
4. Repeat step 3 for all your beacons

**Comment by JulianSobott** [comment]
Sollen wir unsere App und Webseite auf Englisch oder auf Deutsch machen?
Beides könnten wir später auch machen wird dann aber aufwändiger

**Comment by erikgoe** [comment]
Gute Frage, prinzipiell finde ich Englisch besser. Unsere App ist auch schon auf Englisch
