### ISSUE TITLE
Karten Format

### ISSUE THREAD

**Issue by JulianSobott** [JulianSobott/NavEvent#3]
Welche informationen muss die Datei mit der Karte enthalten und wie fügen wir diese der Datei hinzu

**Comment by erikgoe** [comment]
Daten | Beschreibung 
----- | ------------
Metadaten | Name, ID, ggf. kurze Beschreibung, MajorBeaconId
Bild der Karte | optimal wenn in _der_ Datei, sonst in zusätzlicher Datei gespeichert 
Liste aller Beacons | Name, ID, Kartenposition, MinorBeaconId, Zusatzinformationen (Bottom Sheet)
Spezielle Orte | Namen + BeaconIds. Z. B. Ausgänge, Toiletten 
Besondere Orte | Namen + BeaconIds. Z. B. zentrale Vorträge

* Bei besondere und spezielle Orte: Entscheiden ob auf Beacons oder auf Karten-Koordinaten verwiesen wird. 
* Siehe Interfaces (MapData, BeaconData) für ggf. weitere Daten

**Comment by erikgoe** [comment]
[NavEvent/NavEvent/app/src/main/java/com/unknown/navevent/bLogic/services/MapIR.java](Karte)
[NavEvent/NavEvent/app/src/main/java/com/unknown/navevent/bLogic/services/MapBeaconIR.java](Beacon)

Also daraus bräuchte ich für die Beacons:
* Name
* ID
* MinorID (beacon)
* Position X&Y
* Beschreibungstext
* Zu welcher Karte gehört

Und für die Maps:
* Name
* ID
* Beschreibung
* Bild-Dateiname
* MajorID (beacon)

Und wie die Speziellen/Besonderen Orte in der Datenbank gespeichert werden sollen, müssen wir noch überlegen
